---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: again2-ui258-api114
  name: ui-again2-ui258-api114
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-258-merge-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: again2-ui258-api114
  name: ui
  namespace: ui-again2-ui258-api114
spec:
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: master
  releaseName: ui
  values:
    biomageCi:
      repo: biomage-ltd/ui
      sandboxId: again2-ui258-api114
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-258-merge-a946526a13b38891df8539959e21d6f4dbcbd223
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/ui-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: again2-ui258-api114
  name: api-again2-ui258-api114
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-114-merge-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: again2-ui258-api114
  name: api
  namespace: api-again2-ui258-api114
spec:
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: refs/pull/114/head
  releaseName: api
  values:
    biomageCi:
      repo: biomage-ltd/api
      sandboxId: again2-ui258-api114
    hpa:
      enabled: true
      maxReplicas: 10
      minReplicas: 1
      targetCPUUtilizationPercentage: 80
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-pull-114-merge-85b2db3ff95c36f419d760574396c3b9e87e0087
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      path: /v1/health
    readinessProbe:
      path: /v1/health
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/api-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: again2-ui258-api114
  name: worker-again2-ui258-api114
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-develop-*-python
    filter.fluxcd.io/r: glob:refs-heads-develop-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: again2-ui258-api114
  name: worker
  namespace: worker-again2-ui258-api114
spec:
  chart:
    git: git@github.com:biomage-ltd/worker
    path: chart-infra/
    ref: 406349507609c54b4cff5e2d8a7b5e4abf12b74f
  releaseName: worker
  values:
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-develop-406349507609c54b4cff5e2d8a7b5e4abf12b74f-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-develop-406349507609c54b4cff5e2d8a7b5e4abf12b74f-r
    sandboxId: again2-ui258-api114
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: again2-ui258-api114
  name: pipeline-again2-ui258-api114
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/qc-runner: glob:refs-heads-develop-*-qc-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: again2-ui258-api114
  name: pipeline
  namespace: pipeline-again2-ui258-api114
spec:
  chart:
    git: git@github.com:biomage-ltd/pipeline
    path: chart-infra/
    ref: 87f89daf1e083d8ebaeea00d444b457e92aa1c3c
  releaseName: pipeline
  values:
    qc-runner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-develop-87f89daf1e083d8ebaeea00d444b457e92aa1c3c-qc-runner
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
