---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: gem2s-endpoint
  name: ui-gem2s-endpoint
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-develop-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: gem2s-endpoint
  name: ui
  namespace: ui-gem2s-endpoint
spec:
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: d484812cd45f76c5e9c550b61d812d855fe86672
  releaseName: ui
  values:
    biomageCi:
      repo: biomage-ltd/ui
      sandboxId: gem2s-endpoint
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-heads-develop-d2139fd96d428c7b0af2840d35daef95557e5fc7
    kubernetes:
      env: staging
    livenessProbe:
      path: /data-management
    readinessProbe:
      path: /data-management
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/ui-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: gem2s-endpoint
  name: api-gem2s-endpoint
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-109-merge-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: gem2s-endpoint
  name: api
  namespace: api-gem2s-endpoint
spec:
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: refs/heads/master
  releaseName: api
  values:
    biomageCi:
      repo: biomage-ltd/api
      sandboxId: gem2s-endpoint
    hpa:
      enabled: true
      maxReplicas: 10
      minReplicas: 1
      targetCPUUtilizationPercentage: 80
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-pull-109-merge-2ec44c3f7268085308f9fe14d80bb9e257b490f6
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      path: /v1/health
    readinessProbe:
      path: /v1/health
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/api-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: gem2s-endpoint
  name: worker-gem2s-endpoint
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-develop-*-python
    filter.fluxcd.io/r: glob:refs-heads-develop-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: gem2s-endpoint
  name: worker
  namespace: worker-gem2s-endpoint
spec:
  chart:
    git: git@github.com:biomage-ltd/worker
    path: chart-infra/
    ref: 52cb31678872f81d96f41a2e69c781501dd1ee0a
  releaseName: worker
  values:
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-develop-52cb31678872f81d96f41a2e69c781501dd1ee0a-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-develop-52cb31678872f81d96f41a2e69c781501dd1ee0a-r
    sandboxId: gem2s-endpoint
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: gem2s-endpoint
  name: pipeline-gem2s-endpoint
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipeline-runner: glob:refs-pull-56-merge-*-pipeline-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: gem2s-endpoint
  name: pipeline
  namespace: pipeline-gem2s-endpoint
spec:
  chart:
    git: git@github.com:biomage-ltd/pipeline
    path: chart-infra/
    ref: refs/pull/56/head
  releaseName: pipeline
  values:
    pipeline-runner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-pull-56-merge-05f93dec99018c130e1baf489013350ebff52c91-pipeline-runner
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
