apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: marcellp-uidevelop-apideve
  name: ui-marcellp-uidevelop-apideve
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-develop-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: marcellp-uidevelop-apideve
  name: ui
  namespace: ui-marcellp-uidevelop-apideve
spec:
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: 99def6f9a31c5533594dae44f140a0c1dbf3c8f8
  releaseName: ui
  values:
    biomageCi:
      repo: biomage-ltd/ui
      sandboxId: marcellp-uidevelop-apideve
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-heads-develop-6061ea554cecd6b571a29c3fbfb448ab4af66f00
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/ui-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: marcellp-uidevelop-apideve
  name: api-marcellp-uidevelop-apideve
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-develop-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: marcellp-uidevelop-apideve
  name: api
  namespace: api-marcellp-uidevelop-apideve
spec:
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: 99def6f9a31c5533594dae44f140a0c1dbf3c8f8
  releaseName: api
  values:
    biomageCi:
      repo: biomage-ltd/api
      sandboxId: marcellp-uidevelop-apideve
    hpa:
      enabled: true
      maxReplicas: 10
      minReplicas: 1
      targetCPUUtilizationPercentage: 80
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-develop-3c78514c9e4895e916ec30e0ea1bb9a70c9d68de
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      path: /v1/health
    readinessProbe:
      path: /v1/health
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/api-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: marcellp-uidevelop-apideve
  name: worker-marcellp-uidevelop-apideve
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-pull-125-merge-*-python
    filter.fluxcd.io/r: glob:refs-pull-125-merge-*-r
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: marcellp-uidevelop-apideve
  name: worker
  namespace: worker-marcellp-uidevelop-apideve
spec:
  chart:
    git: git@github.com:biomage-ltd/worker
    path: chart-infra/
    ref: refs/pull/125/head
  releaseName: worker
  values:
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-125-merge-f52d2989a1f7d77af3bc99d647b6ff99b335a41f-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-125-merge-f52d2989a1f7d77af3bc99d647b6ff99b335a41f-r
    sandboxId: marcellp-uidevelop-apideve
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: marcellp-uidevelop-apideve
  name: pipeline-marcellp-uidevelop-apideve
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/qc-runner: glob:refs-heads-develop-*-qc-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: marcellp-uidevelop-apideve
  name: pipeline
  namespace: pipeline-marcellp-uidevelop-apideve
spec:
  chart:
    git: git@github.com:biomage-ltd/pipeline
    path: chart-infra/
    ref: 176337cfd492f8a2e08368c7796f0db657e77803
  releaseName: pipeline
  values:
    qc-runner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-develop-176337cfd492f8a2e08368c7796f0db657e77803-qc-runner
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
