apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: stable-demo
  name: ui-stable-demo
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: stable-demo
  name: ui
  namespace: ui-stable-demo
spec:
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: 740297168d541ae7832bc0078e85494ca38294dd
  releaseName: ui
  values:
    biomageCi:
      repo: biomage-ltd/ui
      sandboxId: stable-demo
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-heads-master-57d9e8df13e877690e49f9ac06b4598651efb1aa
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/ui-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: stable-demo
  name: api-stable-demo
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: stable-demo
  name: api
  namespace: api-stable-demo
spec:
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: 740297168d541ae7832bc0078e85494ca38294dd
  releaseName: api
  values:
    biomageCi:
      repo: biomage-ltd/api
      sandboxId: stable-demo
    hpa:
      enabled: true
      maxReplicas: 10
      minReplicas: 1
      targetCPUUtilizationPercentage: 80
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-master-d81c3b8db5622d7da8aee542af542149b8e92d9e
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      path: /v1/health
    readinessProbe:
      path: /v1/health
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/api-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: stable-demo
  name: worker-stable-demo
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-master-*-python
    filter.fluxcd.io/r: glob:refs-heads-master-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: stable-demo
  name: worker
  namespace: worker-stable-demo
spec:
  chart:
    git: git@github.com:biomage-ltd/worker
    path: chart-infra/
    ref: 80b31b41cc8fe82682190eaa3a28927e3c8c0762
  releaseName: worker
  values:
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-80b31b41cc8fe82682190eaa3a28927e3c8c0762-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-80b31b41cc8fe82682190eaa3a28927e3c8c0762-r
    sandboxId: stable-demo
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: stable-demo
  name: pipeline-stable-demo
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/qc-runner: glob:refs-heads-master-*-qc-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: stable-demo
  name: pipeline
  namespace: pipeline-stable-demo
spec:
  chart:
    git: git@github.com:biomage-ltd/pipeline
    path: chart-infra/
    ref: 4e8b601becd674f30aef6ffd91f2b543d6d2969d
  releaseName: pipeline
  values:
    qc-runner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-4e8b601becd674f30aef6ffd91f2b543d6d2969d-qc-runner
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
