apiVersion: v1
kind: Namespace
metadata:
  name: worker-default
  labels:
    sandboxId: default
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/r: glob:refs-heads-develop-*-r
    filter.fluxcd.io/python: glob:refs-heads-develop-*-python
  labels:
    sandboxId: default
spec:
  releaseName: worker
  chart:
    git: git@github.com:biomage-ltd/worker
    path: chart-infra/
    ref: 3a9310e0f52ff399f6923f3be5fcb64930e8e775
  values:
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
    sandboxId: default
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-develop-3a9310e0f52ff399f6923f3be5fcb64930e8e775-r
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-develop-3a9310e0f52ff399f6923f3be5fcb64930e8e775-python
