---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: xavier-ui222
  name: ui-xavier-ui222
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-222-merge-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: xavier-ui222
  name: ui
  namespace: ui-xavier-ui222
spec:
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: master
  releaseName: ui
  values:
    biomageCi:
      repo: biomage-ltd/ui
      sandboxId: xavier-ui222
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-222-merge-4dc158e7ce7eea7eb7bf41068acf9a5cad60fd9e
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/ui-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: xavier-ui222
  name: api-xavier-ui222
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: xavier-ui222
  name: api
  namespace: api-xavier-ui222
spec:
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: d2f549d7fbb3f16ab7fc1fcfaa4f3a55bd3c888e
  releaseName: api
  values:
    biomageCi:
      repo: biomage-ltd/api
      sandboxId: xavier-ui222
    hpa:
      enabled: true
      maxReplicas: 10
      minReplicas: 1
      targetCPUUtilizationPercentage: 80
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-master-d81c3b8db5622d7da8aee542af542149b8e92d9e
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      path: /v1/health
    readinessProbe:
      path: /v1/health
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/api-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: xavier-ui222
  name: worker-xavier-ui222
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-master-*-python
    filter.fluxcd.io/r: glob:refs-heads-master-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: xavier-ui222
  name: worker
  namespace: worker-xavier-ui222
spec:
  chart:
    git: git@github.com:biomage-ltd/worker
    path: chart-infra/
    ref: af0b23516e29645a1d340ecdeb9b8822fc1a5abd
  releaseName: worker
  values:
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-af0b23516e29645a1d340ecdeb9b8822fc1a5abd-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-af0b23516e29645a1d340ecdeb9b8822fc1a5abd-r
    sandboxId: xavier-ui222
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: xavier-ui222
  name: pipeline-xavier-ui222
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/qc-runner: glob:refs-heads-master-*-qc-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: xavier-ui222
  name: pipeline
  namespace: pipeline-xavier-ui222
spec:
  chart:
    git: git@github.com:biomage-ltd/pipeline
    path: chart-infra/
    ref: 4e8b601becd674f30aef6ffd91f2b543d6d2969d
  releaseName: pipeline
  values:
    qc-runner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-4e8b601becd674f30aef6ffd91f2b543d6d2969d-qc-runner
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
