---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: xavier-ui232-e2e
  name: ui-xavier-ui232-e2e
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-232-merge-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: xavier-ui232-e2e
  name: ui
  namespace: ui-xavier-ui232-e2e
spec:
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: master
  releaseName: ui
  values:
    biomageCi:
      repo: biomage-ltd/ui
      sandboxId: xavier-ui232-e2e
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-232-merge-f3b1ab93dc7d1c809df7ebacfb543925406a9e7c
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/ui-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: xavier-ui232-e2e
  name: api-xavier-ui232-e2e
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: xavier-ui232-e2e
  name: api
  namespace: api-xavier-ui232-e2e
spec:
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: d001f450cdbdb1f10085cc55a938c3f4e62a019b
  releaseName: api
  values:
    biomageCi:
      repo: biomage-ltd/api
      sandboxId: xavier-ui232-e2e
    hpa:
      enabled: true
      maxReplicas: 10
      minReplicas: 1
      targetCPUUtilizationPercentage: 80
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-master-d81c3b8db5622d7da8aee542af542149b8e92d9e
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      path: /v1/health
    readinessProbe:
      path: /v1/health
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/api-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: xavier-ui232-e2e
  name: worker-xavier-ui232-e2e
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-master-*-python
    filter.fluxcd.io/r: glob:refs-heads-master-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: xavier-ui232-e2e
  name: worker
  namespace: worker-xavier-ui232-e2e
spec:
  chart:
    git: git@github.com:biomage-ltd/worker
    path: chart-infra/
    ref: 930139e4a5db8eda6f88fe5dac64a098cf38482c
  releaseName: worker
  values:
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-930139e4a5db8eda6f88fe5dac64a098cf38482c-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-930139e4a5db8eda6f88fe5dac64a098cf38482c-r
    sandboxId: xavier-ui232-e2e
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: xavier-ui232-e2e
  name: pipeline-xavier-ui232-e2e
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/qc-runner: glob:refs-heads-master-*-qc-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: xavier-ui232-e2e
  name: pipeline
  namespace: pipeline-xavier-ui232-e2e
spec:
  chart:
    git: git@github.com:biomage-ltd/pipeline
    path: chart-infra/
    ref: 29467d7501cf96550e73c76c29eb196e02848d80
  releaseName: pipeline
  values:
    qc-runner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-29467d7501cf96550e73c76c29eb196e02848d80-qc-runner
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
