apiVersion: v1
kind: Namespace
metadata:
  name: api-default
  labels:
    sandboxId: default
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: api
  namespace: api-default
  labels:
    sandboxId: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
spec:
  releaseName: api
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: master
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: "/v1/health"
    livenessProbe:
      path: "/v1/health"
    resources:
      requests:
        cpu: "100m"
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
    kubernetes:
      env: production
    biomageCi:
      repo: biomage-ltd/api
      sandboxId: default
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-master-4cc1a72d48b8ecbaea3416919c8b83499c2f6675
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/api-role-production

# filled in by CI. do not modify.
