---
apiVersion: v1
kind: Namespace
metadata:
  name: worker-default
  labels:
    sandboxId: default
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/r: glob:refs-heads-master-*-r
    filter.fluxcd.io/python: glob:refs-heads-master-*-python
  labels:
    sandboxId: default
spec:
  releaseName: worker
  chart:
    git: git@github.com:biomage-ltd/worker
    path: chart-infra/
    ref: 9a88ded79259fb2ea3bbae14a68e8ea95d7e39fe
  values:
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-production
    sandboxId: default
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-c1f821a61db317afd5e0477cf4913e69a0f14e11-r
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-9a88ded79259fb2ea3bbae14a68e8ea95d7e39fe-python
