apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-STAGING_SANDBOX_ID
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/remoter-server: glob:refs-heads-master-*-remoter-server
    filter.fluxcd.io/remoter-client: glob:refs-heads-master-*-remoter-client
  labels:
    sandboxId: STAGING_SANDBOX_ID
spec:
  releaseName: pipeline
  chart:
    git: git@github.com:biomage-ltd/pipeline
    path: chart-infra/
    ref: 6e4be6889ef92d4737d772941087429725dfeede
  values:
    remoter-server:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-6e4be6889ef92d4737d772941087429725dfeede-remoter-server
    remoter-client:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-6e4be6889ef92d4737d772941087429725dfeede-remoter-client
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
