apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-STAGING_SANDBOX_ID
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/remoter-server: glob:refs-pull-19-merge-*-remoter-server
    filter.fluxcd.io/remoter-client: glob:refs-pull-19-merge-*-remoter-client
  labels:
    sandboxId: STAGING_SANDBOX_ID
spec:
  releaseName: pipeline
  chart:
    git: git@github.com:biomage-ltd/pipeline
    path: chart-infra/
    ref: STAGING_CHART_REF
  values:
    remoter-server:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-pull-19-merge-db3e80e84d5dc3219b8e26d2f4e731fef4a13602-remoter-server
    remoter-client:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-pull-19-merge-db3e80e84d5dc3219b8e26d2f4e731fef4a13602-remoter-client
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
