apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-STAGING_SANDBOX_ID
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/qc-runner: glob:refs-pull-41-merge-*-qc-runner
  labels:
    sandboxId: STAGING_SANDBOX_ID
spec:
  releaseName: pipeline
  chart:
    git: git@github.com:biomage-ltd/pipeline
    path: chart-infra/
    ref: STAGING_CHART_REF
  values:
    qc-runner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-pull-41-merge-34c9930817c0dbf859c325179503866f9e3add3b-qc-runner
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
