apiVersion: v1
kind: Namespace
metadata:
  name: ui-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:refs-pull-261-merge-*
spec:
  releaseName: ui
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: STAGING_CHART_REF
  values:
    readinessProbe:
      path: "/data-management"
    livenessProbe:
      path: "/data-management"
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-ltd/ui
      sandboxId: STAGING_SANDBOX_ID
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-261-merge-6a431c5b20a164e74074114cd748f2075c28d876
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/ui-role-staging

# filled in by CI. do not modify.
