apiVersion: v1
kind: Namespace
metadata:
  name: api-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: api
  namespace: api-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:refs-pull-84-merge-*
spec:
  releaseName: api
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: STAGING_CHART_REF
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: "/v1/health"
    livenessProbe:
      path: "/v1/health"
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-ltd/api
      sandboxId: STAGING_SANDBOX_ID
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-pull-84-merge-b006453f7505fc2a6c19b76ca045859b201a9ec1
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/api-role-staging

# filled in by CI. do not modify.
