apiVersion: v1
kind: Namespace
metadata:
  name: api-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: api
  namespace: api-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:refs-pull-74-merge-*
spec:
  releaseName: api
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: STAGING_CHART_REF
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: "/v1/health"
    livenessProbe:
      path: "/v1/health"
    kubernetes:
      env: staging
    biomageCi:
      repo: biomage-ltd/api
      sandboxId: STAGING_SANDBOX_ID
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-pull-74-merge-44db14dffe42cbd767ce9efba1f71c71d52976d9
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/api-role-staging

# filled in by CI. do not modify.
