apiVersion: v1
kind: Namespace
metadata:
  name: worker-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-STAGING_SANDBOX_ID
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/r: glob:refs-pull-102-merge-*-r
    filter.fluxcd.io/python: glob:refs-pull-102-merge-*-python
  labels:
    sandboxId: STAGING_SANDBOX_ID
spec:
  releaseName: worker
  chart:
    git: git@github.com:biomage-ltd/worker
    path: chart-infra/
    ref: STAGING_CHART_REF
  values:
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
    sandboxId: STAGING_SANDBOX_ID
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-102-merge-369578124b1feebb1debb2a2e375d4bdee75055e-r
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-102-merge-369578124b1feebb1debb2a2e375d4bdee75055e-python
