apiVersion: v1
kind: Namespace
metadata:
  name: worker-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-STAGING_SANDBOX_ID
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/r: glob:refs-heads-master-*-r
    filter.fluxcd.io/python: glob:refs-heads-master-*-python
  labels:
    sandboxId: STAGING_SANDBOX_ID
spec:
  releaseName: worker
  chart:
    git: git@github.com:biomage-ltd/worker
    path: chart-infra/
    ref: 930139e4a5db8eda6f88fe5dac64a098cf38482c
  values:
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
    sandboxId: STAGING_SANDBOX_ID
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-930139e4a5db8eda6f88fe5dac64a098cf38482c-r
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-930139e4a5db8eda6f88fe5dac64a098cf38482c-python
